# menus ID
ABOUT_US_ID 				= 1
MEDIA_CENTER_ID 			= 2
STORIES_ID 					= 3
NEWS_ID 					= 4
LEARN_CENTER_ID 			= 5
MINIATURE_ENTERPRISE_ID		= 6
SOCIAL_ENTERPRISE_ID 		= 7
CONTACT_US_ID 				= 8

# articles id
ABOUT_US_ARTICLE_ID 		= 0
